using System;
using System.Collections.Generic;
using System.Text;

namespace TC.Magneto
{
	/// <summary>Represents an error generated by one of the Magneto-components.</summary>
	public class MagnetoException : Exception
	{
		/// <summary>Initializes a new instance of the <see cref="MagnetoException"/> class.</summary>
		/// <param name="message">The error message.</param>
		public MagnetoException(string message) : this(message, TextPosition.Empty) { }

		/// <summary>Initializes a new instance of the <see cref="MagnetoException"/> class.</summary>
		/// <param name="message">The error message.</param>
		/// <param name="position">The position.</param>
		public MagnetoException(string message, TextPosition position)
			: base(message)
		{
			this.position = position;
		}

		readonly TextPosition position;
		/// <summary>Gets the position.</summary>
		/// <value>The position.</value>
		public TextPosition Position { get { return position; } }
	}
}
